# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Matteo Pannacci
title: Master's Student in Artificial Intelligence and Robotics at Sapienza Università di Roma
email: matteo.pannacci@gmail.com
website: matteopannacci.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  MatteoPannacci
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: matteo-pannacci
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0002-8426-7329
googlescholar_username: _VlMoTYAAAAJ

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Work in Progress


content:

  #############
  # Education #
  #############

  - title: Education
    layout: list
    content:

      # master's degree
      - layout: left
        title: M.Sc. AI and Robotics
        caption: 2023 - 2025
        sub_title: Sapienza Università di Roma
        description: |
          GPA: 30/30
          
          Currently enrolled as a second year student following the Honours' Programme.

      # bachelor's degree
      - layout: left
        title: B.Sc. Computer and System Engineering
        caption: 2020 - 2023
        sub_title: Sapienza Università di Roma
        description: |
          Grade: 110 / 110 cum laude

      # high school
      - layout: left
        title: High School Diploma, Liceo Scientifico Tradizionale
        caption: 2015 - 2020
        sub_title: Liceo Statale Democrito
        description: |
          Grade: 100 / 100 cum laude


  ################
  # Publications #
  ################

  - title: Publications
    layout: text
    content: |
      Emanuele Mule<sup>*</sup>, Matteo Pannacci<sup>*</sup>, Ali Ghasemi Goudarzi<sup>*</sup>, Francesco Pro, Lorenzo Papa, Luca Maiano and Irene Amerini. Enhancing ground-to-aerial image matching for visual misinformation detection using semantic segmentation, 2025. <a href="https://arxiv.org/pdf/2502.06288" target="_blank"></a>

      <sup>*</sup>: Equal contribution


#  # Publications
#  - title: Publications
#    layout: list
#    content: 
#      - layout: top-middle
#        border: weak
#        title: Enhancing Ground-to-Aerial Image Matching for Visual Misinformation Detection Using Semantic Segmentation
#        sub_title: Emanuele Mule<sup>*</sup>, Matteo Pannacci<sup>*</sup>, Ali Ghasemi Goudarzi<sup>*</sup>, Francesco Pro, Lorenzo Papa, Luca Maiano and Irene Amerini.
#        description: |
#          This project ...


############
# Projects #
############

  - title: Projects
    layout: list
    content:

      # machiavelli-planning
      - layout: left
        title: Machiavelli Planning
        sub_title: January 2025
        link: github.com/MatteoPannacci/machiavelli-planning
        link_text: Github repository
        description: |
          ...

      # rdfs-in-neo4j
      - layout: left
        title: RDFS in Neo4J
        sub_title: May 2024
        link: github.com/MatteoPannacci/rdfs-in-neo4j
        link_text: Github repository
        description: |
          ...

      # rp-simple-planner
      - layout: left
        title: ROS Simple Planner
        sub_title: September 2024
        link: github.com/MatteoPannacci/rp-simple-planner
        link_text: Github repository
        description: |
          ...


#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
