# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Matteo Pannacci
title: Master's Student in Artificial Intelligence and Robotics at Sapienza Università di Roma
email: matteo.pannacci@gmail.com
website: matteopannacci.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  MatteoPannacci
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: matteo-pannacci
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0002-8426-7329
googlescholar_username: _VlMoTYAAAAJ

# Additional icon links
additional_links:
#- title: Kaggle link
#  icon: fab fa-kaggle
#  url: https://www.kaggle.com/matteopannacci
#- title: HuggingFace link
#  icon: far fa-face-smiling-hands
#  url: https://huggingface.co/Matteo-Pannacci


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Work in Progress


content:

  #############
  # Education #
  #############

  - title: Education
    layout: list
    content:

      # master's degree
      - layout: left
        border: weak
        title: M.Sc. AI and Robotics
        caption: 2023 - Current
        sub_title: Sapienza Università di Roma
        description: |
          Current GPA: 30/30

          ---
          
          Best Student of the course according to Sapienza "Exam Bonus" Award.

          Recipient of Sapienza "Meritorious Students" Merits.

          Currently enrolled as a second year student following the Honours' Programme.

      # bachelor's degree
      - layout: left
        border: weak
        title: B.Sc. Computer and System Engineering
        caption: 2020 - 2023
        sub_title: Sapienza Università di Roma
        description: |
          Final Grade: 110 / 110 cum laude

          Final GPA: 29.29/30

          ---

          Recipient of Sapienza "Meritorious Students" Merits.

      # high school
      - layout: left
        title: High School Diploma, Liceo Scientifico Tradizionale
        caption: 2015 - 2020
        sub_title: Liceo Statale Democrito
        description: |
          Final Grade: 100 / 100 cum laude

          ---

          Throughout high school, I participated in various student competitions in Math, Physics, Biology, Chemistry, and Computer Science at the school, regional, and national levels, both individually and as a team leader.

          During my fourth year of high school, I was selected for and attended the "Scuola Estiva Nazionale per Studenti sulla Fisica Moderna 2019" (SENS-FM2019), which took place at the University of Udine.

  ################
  # Publications #
  ################

  - title: Publications
    layout: text
    content: |
      [1] Emanuele Mule<sup>*</sup>, Matteo Pannacci<sup>*</sup>, Ali Ghasemi Goudarzi<sup>*</sup>, Francesco Pro, Lorenzo Papa, Luca Maiano and Irene Amerini. Enhancing ground-to-aerial image matching for visual misinformation detection using semantic segmentation. In Proceedings of the Winter Conference on Applications of Computer Vision (WACV) Workshops, pages 795-803, February 2025. ([article](https://arxiv.org/pdf/2502.06288), [repository](https://github.com/MatteoPannacci/SemanticAlignNet-QUAD), [website](https://matteopannacci.github.io/SemanticAlignNet-QUAD/))
      
      <sup>*</sup>: Equal contribution


############
# Projects #
############

  - title: Highlighted Projects
    layout: list
    content:

      # machiavelli-planning
      - layout: left
        border: weak
        title: Machiavelli Planning
        sub_title: January 2025
        link: https://github.com/MatteoPannacci/machiavelli-planning
        link_text: Github repository
        description: |
          Implementation in PDDL and IndiGolog of a planning task from the italian card game Machiavelli. 
          We take into consideration a single turn of a player during the course of the game. The goal is to check whether it's possible for the player to win from the current configuration (board state and player's hand) and, in the positive case, to find a sequence of legal actions that do so. 

      # rdfs-in-neo4j
      - layout: left
        border: weak
        title: RDFS in Neo4J
        sub_title: May 2024
        link: https://github.com/MatteoPannacci/rdfs-in-neo4j
        link_text: Github repository
        description: |
          Implementation in Python of 2 class structures representing RDFS-based Knowledge Graphs. The first version uses a Neo4J Session to perform updates, syntax check and deduction directly on the graph through queries in Cypher. The second version performs these operations in Python and is able to interact with a Neo4J Session for importing/exporting Knowledge Graphs.

      # rp-simple-planner
      - layout: left
        border: weak
        title: ROS Simple Planner
        sub_title: September 2024
        link: https://github.com/MatteoPannacci/rp-simple-planner
        link_text: Github repository
        description: |
          Implementation of a simple 2D trajectory planner for ROS in C++. The code provides a node that listens to the required informations (current position, map structure and goal position), then it uses these informations to build the trajectory planning problem and solves it applying the A* algorithm. The resulting path is then visualized using OpenCV.

      # Multi-Family-Co-Evolutionary-RL
      - layout: left
        title: Multi-Family Co-Evolutionary Approach for MARL
        sub_title: December 2024
        link: https://github.com/EmaMule/Multi-Family-Co-Evolutionary-RL
        link_text: Github repository
        description: |
          Implementation of ES (Evolutive Strategy) and GA (Genetic Algorithm) using multiple independent populations in the context of Multi-Agent Reinforcement Learning to train neural networks (Neuro-Evolution). The agents learn to play classic games from the PettingZoo library including Connect Four and TicTacToe by having the populations compete against each other.


#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
